<section class="page break">
    <div class="header">
        <div>
            <div class="kicker">Republic of the Philippines</div>
            <h1 class="title">Personal Data Sheet</h1>
            <p class="subtitle">CSC Form No. 212 (Revised 2017) | Employee-furnished record generated from LTO HRIS</p>
        </div>
        <div class="photo"><?php echo pds_document_image_markup($signature['applicant_photo'] ?? '', 'Applicant photo', $embedImages); ?></div>
    </div>
    <div class="meta">
        <div class="meta-item"><small>Employee ID</small><strong><?php echo pds_document_value($employeeId); ?></strong></div>
        <div class="meta-item"><small>Filing Year</small><strong><?php echo pds_document_value($year); ?></strong></div>
        <div class="meta-item"><small>Record Status</small><strong><?php echo pds_document_value($pdsRecord['status'] ?? 'draft'); ?></strong></div>
        <div class="meta-item"><small>Date Signed</small><strong><?php echo pds_document_date($signature['date_signed'] ?? ''); ?></strong></div>
    </div>
    <section class="section"><h3>I. Personal Information</h3><div class="grid">
        <div class="field"><div class="label">Surname</div><div class="value"><?php echo pds_document_value($personal['surname'] ?? ''); ?></div></div>
        <div class="field"><div class="label">First Name</div><div class="value"><?php echo pds_document_value($personal['first_name'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Middle Name</div><div class="value"><?php echo pds_document_value($personal['middle_name'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Extension</div><div class="value"><?php echo pds_document_value($personal['name_extension'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Date of Birth</div><div class="value"><?php echo pds_document_date($personal['date_of_birth'] ?? ''); ?></div></div>
        <div class="field half"><div class="label">Place of Birth</div><div class="value"><?php echo pds_document_value($personal['place_of_birth'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Sex</div><div class="value"><?php echo pds_document_value($personal['sex'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Civil Status</div><div class="value"><?php echo pds_document_value($personal['civil_status'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Citizenship</div><div class="value"><?php echo pds_document_value($personal['citizenship'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Height (m)</div><div class="value"><?php echo pds_document_value($personal['height_m'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Weight (kg)</div><div class="value"><?php echo pds_document_value($personal['weight_kg'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Blood Type</div><div class="value"><?php echo pds_document_value($personal['blood_type'] ?? ''); ?></div></div>
        <div class="field"><div class="label">GSIS ID</div><div class="value"><?php echo pds_document_value($personal['gsis_id'] ?? ''); ?></div></div>
        <div class="field"><div class="label">PAG-IBIG ID</div><div class="value"><?php echo pds_document_value($personal['pagibig_id'] ?? ''); ?></div></div>
        <div class="field"><div class="label">PhilHealth No.</div><div class="value"><?php echo pds_document_value($personal['philhealth_id'] ?? ''); ?></div></div>
        <div class="field"><div class="label">SSS No.</div><div class="value"><?php echo pds_document_value($personal['sss_id'] ?? ''); ?></div></div>
        <div class="field"><div class="label">TIN No.</div><div class="value"><?php echo pds_document_value($personal['tin_id'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Agency Employee No.</div><div class="value"><?php echo pds_document_value($personal['agency_employee_no'] ?? ''); ?></div></div>
        <div class="field full"><div class="label">Residential Address</div><div class="value"><?php echo pds_document_value($personal['residential_address'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Residential Zip Code</div><div class="value"><?php echo pds_document_value($personal['residential_zip_code'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Residential Telephone</div><div class="value"><?php echo pds_document_value($personal['residential_telephone'] ?? ''); ?></div></div>
        <div class="field full"><div class="label">Permanent Address</div><div class="value"><?php echo pds_document_value($personal['permanent_address'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Permanent Zip Code</div><div class="value"><?php echo pds_document_value($personal['permanent_zip_code'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Permanent Telephone</div><div class="value"><?php echo pds_document_value($personal['permanent_telephone'] ?? ''); ?></div></div>
        <div class="field half"><div class="label">Email Address</div><div class="value"><?php echo pds_document_value($personal['email_address'] ?? ''); ?></div></div>
        <div class="field half"><div class="label">Mobile Number</div><div class="value"><?php echo pds_document_value($personal['mobile_number'] ?? ''); ?></div></div>
    </div></section>
    <section class="section"><h3>II. Family Background</h3><div class="grid">
        <div class="field"><div class="label">Spouse Surname</div><div class="value"><?php echo pds_document_value($family['spouse_surname'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Spouse First Name</div><div class="value"><?php echo pds_document_value($family['spouse_first_name'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Spouse Middle Name</div><div class="value"><?php echo pds_document_value($family['spouse_middle_name'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Spouse Extension</div><div class="value"><?php echo pds_document_value($family['spouse_name_extension'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Occupation</div><div class="value"><?php echo pds_document_value($family['spouse_occupation'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Employer / Business</div><div class="value"><?php echo pds_document_value($family['spouse_employer_business_name'] ?? ''); ?></div></div>
        <div class="field half"><div class="label">Business Address</div><div class="value"><?php echo pds_document_value($family['spouse_business_address'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Telephone</div><div class="value"><?php echo pds_document_value($family['spouse_telephone'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Father's Surname</div><div class="value"><?php echo pds_document_value($family['father_surname'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Father's First Name</div><div class="value"><?php echo pds_document_value($family['father_first_name'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Father's Middle Name</div><div class="value"><?php echo pds_document_value($family['father_middle_name'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Father's Extension</div><div class="value"><?php echo pds_document_value($family['father_name_extension'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Mother's Maiden Surname</div><div class="value"><?php echo pds_document_value($family['mother_maiden_surname'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Mother's First Name</div><div class="value"><?php echo pds_document_value($family['mother_first_name'] ?? ''); ?></div></div>
        <div class="field"><div class="label">Mother's Middle Name</div><div class="value"><?php echo pds_document_value($family['mother_middle_name'] ?? ''); ?></div></div>
    </div><div class="note">Children are listed in chronological order based on date of birth.</div><div class="list">
        <?php if (!empty($children)): foreach ($children as $child): ?><div class="list-item"><strong><?php echo pds_document_value($child['child_name'] ?? ''); ?></strong><div class="value">Date of Birth: <?php echo pds_document_date($child['date_of_birth'] ?? ''); ?></div></div><?php endforeach; else: ?><div class="list-item">No children listed.</div><?php endif; ?>
    </div></section><div class="footer"><span>Generated from LTO HRIS PDS record</span><span>Page 1 of 4</span></div>
</section>
<section class="page break">
    <section class="section"><h3>III. Educational Background</h3><table><thead><tr><th>Level</th><th>School Name</th><th>Degree / Course</th><th>From</th><th>To</th><th>Units Earned</th><th>Year Graduated</th><th>Honors</th></tr></thead><tbody><?php if (!empty($education)): foreach ($education as $row): ?><tr><td><?php echo pds_document_value($row['level'] ?? ''); ?></td><td><?php echo pds_document_value($row['school_name'] ?? ''); ?></td><td><?php echo pds_document_value($row['degree_course'] ?? ''); ?></td><td><?php echo pds_document_date($row['period_from'] ?? ''); ?></td><td><?php echo pds_document_date($row['period_to'] ?? ''); ?></td><td><?php echo pds_document_value($row['highest_level_units_earned'] ?? ''); ?></td><td><?php echo pds_document_value($row['year_graduated'] ?? ''); ?></td><td><?php echo pds_document_value($row['scholarship_academic_honors'] ?? ''); ?></td></tr><?php endforeach; else: ?><tr><td colspan="8">No educational background recorded.</td></tr><?php endif; ?></tbody></table></section>
    <section class="section"><h3>IV. Civil Service Eligibility</h3><table><thead><tr><th>Career Service</th><th>Rating</th><th>Date of Exam / Conferment</th><th>Place of Exam / Conferment</th><th>License Number</th><th>Date of Release</th></tr></thead><tbody><?php if (!empty($eligibility)): foreach ($eligibility as $row): ?><tr><td><?php echo pds_document_value($row['career_service'] ?? ''); ?></td><td><?php echo pds_document_value($row['rating'] ?? ''); ?></td><td><?php echo pds_document_date($row['date_of_examination_conferment'] ?? ''); ?></td><td><?php echo pds_document_value($row['place_of_examination_conferment'] ?? ''); ?></td><td><?php echo pds_document_value($row['license_number'] ?? ''); ?></td><td><?php echo pds_document_date($row['date_of_release'] ?? ''); ?></td></tr><?php endforeach; else: ?><tr><td colspan="6">No civil service eligibility recorded.</td></tr><?php endif; ?></tbody></table></section>
    <div class="footer"><span>Generated from LTO HRIS PDS record</span><span>Page 2 of 4</span></div>
</section>
<section class="page break">
    <section class="section"><h3>V. Work Experience</h3><table><thead><tr><th>From</th><th>To</th><th>Position Title</th><th>Department / Agency / Office</th><th>Monthly Salary</th><th>Salary Grade</th><th>Step</th><th>Status</th><th>Gov't Service</th></tr></thead><tbody><?php if (!empty($workExperience)): foreach ($workExperience as $row): ?><tr><td><?php echo pds_document_date($row['inclusive_dates_from'] ?? ''); ?></td><td><?php echo pds_document_date($row['inclusive_dates_to'] ?? ''); ?></td><td><?php echo pds_document_value($row['position_title'] ?? ''); ?></td><td><?php echo pds_document_value($row['department_agency_office'] ?? ''); ?></td><td><?php echo pds_document_value($row['monthly_salary'] ?? ''); ?></td><td><?php echo pds_document_value($row['salary_grade'] ?? ''); ?></td><td><?php echo pds_document_value($row['step_increment'] ?? ''); ?></td><td><?php echo pds_document_value($row['status_of_appointment'] ?? ''); ?></td><td><?php echo pds_document_value($row['government_service'] ?? ''); ?></td></tr><?php endforeach; else: ?><tr><td colspan="9">No work experience recorded.</td></tr><?php endif; ?></tbody></table></section>
    <section class="section"><h3>VI. Voluntary Work</h3><table><thead><tr><th>Organization / Address</th><th>From</th><th>To</th><th>No. of Hours</th><th>Position / Nature of Work</th></tr></thead><tbody><?php if (!empty($voluntaryWork)): foreach ($voluntaryWork as $row): ?><tr><td><?php echo pds_document_value($row['name_organization_address'] ?? ''); ?></td><td><?php echo pds_document_date($row['inclusive_dates_from'] ?? ''); ?></td><td><?php echo pds_document_date($row['inclusive_dates_to'] ?? ''); ?></td><td><?php echo pds_document_value($row['number_of_hours'] ?? ''); ?></td><td><?php echo pds_document_value($row['position_nature_of_work'] ?? ''); ?></td></tr><?php endforeach; else: ?><tr><td colspan="5">No voluntary work recorded.</td></tr><?php endif; ?></tbody></table></section>
    <section class="section"><h3>VII. Learning and Development Programs</h3><table><thead><tr><th>Program Title</th><th>From</th><th>To</th><th>No. of Hours</th><th>Type</th><th>Sponsored By</th></tr></thead><tbody><?php if (!empty($training)): foreach ($training as $row): ?><tr><td><?php echo pds_document_value($row['title_of_learning_development_programs'] ?? ''); ?></td><td><?php echo pds_document_date($row['inclusive_dates_from'] ?? ''); ?></td><td><?php echo pds_document_date($row['inclusive_dates_to'] ?? ''); ?></td><td><?php echo pds_document_value($row['number_of_hours'] ?? ''); ?></td><td><?php echo pds_document_value($row['type_of_ld'] ?? ''); ?></td><td><?php echo pds_document_value($row['sponsored_by'] ?? ''); ?></td></tr><?php endforeach; else: ?><tr><td colspan="6">No training programs recorded.</td></tr><?php endif; ?></tbody></table></section>
    <section class="section"><h3>VIII. Other Information</h3><div class="grid"><div class="field full"><div class="label">Special Skills and Hobbies</div><div class="value"><?php echo pds_document_value($otherInfo['special_skills_hobbies'] ?? ''); ?></div></div><div class="field full"><div class="label">Non-Academic Distinctions / Recognitions</div><div class="value"><?php echo pds_document_value($otherInfo['non_academic_distinctions_recognitions'] ?? ''); ?></div></div><div class="field full"><div class="label">Membership in Associations / Organizations</div><div class="value"><?php echo pds_document_value($otherInfo['membership_association_organizations'] ?? ''); ?></div></div></div></section>
    <div class="footer"><span>Generated from LTO HRIS PDS record</span><span>Page 3 of 4</span></div>
</section>
<section class="page">
    <section class="section"><h3>IX. Questions</h3>
        <div class="q"><strong>34. Related by consanguinity or affinity to appointing authority or any public official in the same agency?</strong><div>Answer: <?php echo pds_document_yes_no($questions['q34_related_by_blood_marriage'] ?? ''); ?> | Details: <?php echo pds_document_value($questions['q34_relationship_details'] ?? ''); ?></div></div>
        <div class="q"><strong>35. Found guilty of any administrative offense?</strong><div>Answer: <?php echo pds_document_yes_no($questions['q35_guilty_administrative_offense'] ?? ''); ?> | Details: <?php echo pds_document_value($questions['q35_offense_details'] ?? ''); ?></div></div>
        <div class="q"><strong>36. Ever been criminally charged in any court?</strong><div>Answer: <?php echo pds_document_yes_no($questions['q36_criminally_charged'] ?? ''); ?> | Details: <?php echo pds_document_value($questions['q36_case_details'] ?? ''); ?></div></div>
        <div class="q"><strong>37. Ever been convicted of any crime or violation of any law?</strong><div>Answer: <?php echo pds_document_yes_no($questions['q37_convicted_final_judgment'] ?? ''); ?> | Details: <?php echo pds_document_value($questions['q37_case_details'] ?? ''); ?></div></div>
        <div class="q"><strong>38. Ever separated from service?</strong><div>Answer: <?php echo pds_document_yes_no($questions['q38_separated_service'] ?? ''); ?> | Details: <?php echo pds_document_value($questions['q38_reason_details'] ?? ''); ?></div></div>
        <div class="q"><strong>39. Ever been a citizen or holder of dual citizenship of any foreign country?</strong><div>Answer: <?php echo pds_document_yes_no($questions['q39_immigrant_status'] ?? ''); ?> | Details: <?php echo pds_document_value($questions['q39_country_details'] ?? ''); ?></div></div>
        <div class="q"><strong>40. Member of an indigenous group?</strong><div>Answer: <?php echo pds_document_yes_no($questions['q40_indigenous_member'] ?? ''); ?> | Details: <?php echo pds_document_value($questions['q40_group_details'] ?? ''); ?></div></div>
    </section>
    <section class="section"><h3>X. References</h3><table><thead><tr><th>Name</th><th>Address</th><th>Telephone</th></tr></thead><tbody><?php if (!empty($references)): foreach ($references as $row): ?><tr><td><?php echo pds_document_value($row['name'] ?? ''); ?></td><td><?php echo pds_document_value($row['address'] ?? ''); ?></td><td><?php echo pds_document_value($row['telephone'] ?? ''); ?></td></tr><?php endforeach; else: ?><tr><td colspan="3">No references recorded.</td></tr><?php endif; ?></tbody></table></section>
    <section class="section"><h3>XI. Government Issued ID</h3><div class="grid"><div class="field"><div class="label">ID Type</div><div class="value"><?php echo pds_document_value($governmentId['id_type'] ?? ''); ?></div></div><div class="field"><div class="label">ID Number</div><div class="value"><?php echo pds_document_value($governmentId['id_number'] ?? ''); ?></div></div><div class="field"><div class="label">Date Issued</div><div class="value"><?php echo pds_document_date($governmentId['date_issued'] ?? ''); ?></div></div><div class="field"><div class="label">Issuing Authority</div><div class="value"><?php echo pds_document_value($governmentId['issuing_authority'] ?? ''); ?></div></div></div></section>
    <section class="section"><h3>XII. Signature and Thumbmark</h3><div class="sig-grid"><div class="sig-card"><small>Applicant Signature</small><?php echo pds_document_image_markup($signature['applicant_signature'] ?? '', 'Applicant signature', $embedImages); ?></div><div class="sig-card"><small>Thumbmark</small><?php echo pds_document_image_markup($signature['thumbmark'] ?? '', 'Thumbmark', $embedImages); ?></div><div class="sig-card"><small>Date Signed</small><div class="value"><?php echo pds_document_date($signature['date_signed'] ?? ''); ?></div></div></div></section>
    <div class="footer"><span>Generated from LTO HRIS PDS record</span><span>Page 4 of 4</span></div>
</section>
